### ISSUE TITLE
Fail with rolify/cancan option.

### ISSUE THREAD

**Issue by stevenkolstad** [RailsApps/rails3-mongoid-devise#17] opened 2012-04-20 10:28 UTC
```
    gsub    app/models/user.rb
    gsub    app/models/user.rb
    gsub    app/models/user.rb
     run    rails generate devise:views from "."
/app/models/user.rb:2:in `<class:User>': undefined local variable or method `rolify' for User:Class (NameError)
from /app/models/user.rb:1:in `<top (required)>'
```

**Comment by dhf0820** [comment] 2012-05-01 19:37
rolify need to be after the includ mongoid. But this error stops the completion of the generator. I figured I could specify no cancan and rolify getting it to work. It does generate but then fails on invitation_token not found. I am about to give up as there seems to be issues with this generator.

**Comment by l4u** [comment] 2012-05-07 03:50
@dhf0820  for the fails on invitation_token, 
It works for me when the User Model has these field: 
https://gist.github.com/2625795

**Comment by DanielKehoe** [comment] 2012-05-13 20:47
@dhf0820 and @l4u thanks for your patience and understanding, I can't test all possible combinations of the preferences, so I appreciate that you brought this error to my attention. I've updated the application template to correct the error. Please test and let me know if the issue is resolved.

-- Daniel

**Comment by ryudice** [comment] 2012-05-25 02:55
It doesnt work for me still

**Comment by backspace** [comment] 2012-05-26 15:59
Yes, it also doesn’t work for me. I was able to add the controller after I moved `rolify` below `include Mongoid::Document` as suggested above, but can I somehow continue the template after that?

When I answer `n` to the CanCan & Rolify question, it works for me. I don’t expect it to be too difficult to incorporate those after the fact.

**Comment by hosamaly** [comment] 2012-05-29 11:32
The problem is that Rolify 3.1 (which is [required](https://github.com/RailsApps/rails_apps_composer/blob/master/recipes/devise.rb#L25) by the template) [has an issue](https://github.com/EppO/rolify/issues/61) with Mongoid, causing the generation process to fail. The issue has been fixed in Rolify 3.2.0.beta4.

Until Rolify 3.2.0.final is released, an acceptable workaround could be to prepend the call to `rolify` in the user model with `include Mongoid::Document`, as you can see [here](https://github.com/EppO/rolify/commit/7265bb7116d106fc1f7bf01f783523890cc6db4a#L0R40). I think it should be easy to do this using `gsub_file` in the AddUser recipe, right after [the call to](https://github.com/RailsApps/rails_apps_composer/blob/master/recipes/add_user.rb#L31) `generate 'rolify:role Role User mongoid'`

**Comment by ericraio** [comment] 2012-06-10 21:44
This solved the issue for me

https://gist.github.com/2907446

**Comment by DanielKehoe** [comment] 2012-06-11 04:37
I've updated rails_apps_composer and the application templates to incorporate your suggestions. Please test and let me know if the issue is resolved. Thanks for your help and patience!

**Comment by backspace** [comment] 2012-06-12 20:39
Yes, it works for me now, thanks!

**Comment by DanielKehoe** [comment] 2012-06-12 20:51
@backspace Thanks for the feedback. I'll close the issue.

**Closed as completed by DanielKehoe** 2012-06-12 20:51 UTC
