### ISSUE TITLE
FactoryGirl fragile on user model

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-devise#34] opened 2013-01-29 23:00 UTC
When adding Cucumber steps to an app derived from this example app (one of its major use cases), I noticed their user authentication code had changed quite a lot. Generally, it seems this will happen.

The part of the cukes using FactoryGirl no longer worked. Now, I am sure someone familiar with FactoryGirl can keep an altered app's cukes working.

However, for something more easy and direct for newbies, isn't it better to drop FactoryGirl from the user model and use pure Capybara in the Cucumber user steps?

**Comment by schadenfred** [comment] 2013-01-30 04:43
Mark, my instinct is that while using this example app as the base of a new application should work fine, it might be better to instead generate the application per the documentation:

https://github.com/RailsApps/rails3-mongoid-devise#generate

This way, you can customize it to your hearts content, and ignore factory_girl.  Remember, RailsApps is supposed to work for you, not the other way around :)

**Comment by MarkDBlackwell** [comment] 2013-01-30 05:22
@fdshoeneman, I did indeed generate the application per the documentation, as you describe.

I find FactoryGirl then appears in files:

features/step_definitions/user_steps.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb

It's nice to hear you approve of Capybara. So you know the following, which I document for completeness.

After generation, anything can be stripped out. However, giving value to newbies (after they customize the User model and Devise's optional features), IMHO much easier to tailor than FactoryGirl-style user creation is Capybara-style user creation. For example:

visit '/signup'
fill_in 'Name', with: @visitor[:name]
fill_in 'Email', with: @visitor[:email]
click_button 'Sign up'

To accomplish this, FactoryGirl doesn't need to be thrown away, just kept away from the User model in the methods #find_user, #create_user and #delete_user. That's what breaks when the User model is customized. For ease of customization, IMO those methods should use Capybara, too.

Then the FactoryGirl use could be simplified, to be a Ruby Struct, instead.

**Comment by schadenfred** [comment] 2013-01-30 06:14
so you generate the app as described, meaning, without selecting factory girl -- and it still shows up with those methods in features/step_definitions/user_steps.rb?  Or am I confused?  

Does your step definitions file look like this?

https://github.com/RailsApps/rails3-mongoid-devise/blob/master/features/step_definitions/user_steps.rb

**Comment by DanielKehoe** [comment] 2013-01-30 06:39
I'm investigating. factory_girl_rails (4.2.0) was released four days ago and appears to be generating additional files that were not previously created when the Rails Composer template runs.

**Comment by DanielKehoe** [comment] 2013-01-31 05:21
The issue is resolved with the newest release of rails_apps_composer (2.2.31) and the Rails Composer tool. Factory_girl_rails 4.2.0 changed default behavior for generating factories when used with RSpec. See the blog post http://j.mp/Tdqxsz and https://github.com/thoughtbot/factory_girl_rails/issues/88.

**Closed as completed by DanielKehoe** 2013-01-31 05:21 UTC
